---
title: "SMART Weight Loss: Analytics for July 2020 Submission"
author: |
    |
date: '`r format(Sys.Date(), "%B %d, %Y")`'
geometry: margin=0.5in
output: 
  pdf_document:
    number_sections: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r global_options, include=FALSE}
knitr::opts_chunk$set(tidy = TRUE)
knitr::opts_chunk$set(fig.pos = 'H')
```


```{r, echo = FALSE, message = FALSE}
library(rmarkdown)
library(knitr)
library(kableExtra)
library(dplyr)
```

# ROC Curves for Classification Tree

```{r, echo = FALSE, message = FALSE, warning = FALSE, fig.height=4, fig.width=4}
source("month-three.R")
```

\newpage

# How many individuals did we consider and what percentage had missing data?
```{r, echo = FALSE}
missdf %>%
  select(tot_rows, percent_day1, percent_day4, percent_day7, miss_analysis) %>%
  round(., digits = 3) %>%
  kable(booktabs = TRUE, align = rep('c',8),
        col.names = c("Total No. Individuals","No weight on Day 1","No weight on Day 4","No weight on Day 7","No weight on Day 1, 4, or 7"),
        row.names = FALSE,
        escape = FALSE,
        caption = "First Column: Total number of individuals in APP ONLY arm (excluding one individual with data issue); Remaining Columns: Percent with no weights") %>%
  kable_styling(full_width = FALSE, latex_options = c("HOLD_position","scale_down"))
```


# Can we identify App non-responders during the first week of treatment?

```{r, echo = FALSE}
tbl_cart_only %>%
  select(sensitivity,specificity) %>%
  round(., digits = 3) %>%
  kable(booktabs = TRUE, align = rep('c',2),
        col.names = c("Sensitivity","Specificity"),
        row.names = TRUE,
        escape = FALSE,
        caption = "CART Only") %>%
  kable_styling(full_width = FALSE, latex_options = c("HOLD_position"))
```

```{r, echo = FALSE}
tbl_overall %>%
  select(sensitivity,specificity) %>%
  round(., digits = 3) %>%
  kable(booktabs = TRUE, align = rep('c',2),
        col.names = c("Sensitivity","Specificity"),
        row.names = TRUE,
        escape = FALSE,
        caption = "Overall Decision Rule") %>%
  kable_styling(full_width = FALSE, latex_options = c("HOLD_position"))
```

# Is non-response status at week 8 predictive of weight loss at month 3?

```{r, echo = FALSE}
tbl_mod %>%
  round(., digits = 3) %>%
  kable(booktabs = TRUE, align = rep('c',4),
        col.names = c("Estimate", "Std. Error", "z value", "Pr(>|z|)"),
        row.names = TRUE,
        escape = FALSE,
        caption = "Estimates of Parameters in a Logistic Regression Model") %>%
  kable_styling(full_width = FALSE, latex_options = c("HOLD_position"))
```

