---
title: "SMART Weight Loss: Analytics for February 2021 Submission"
author: |
    |
date: '`r format(Sys.Date(), "%B %d, %Y")`'
geometry: margin=0.7in
output: 
  pdf_document:
    number_sections: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r global_options, include=FALSE}
knitr::opts_chunk$set(tidy = TRUE)
knitr::opts_chunk$set(fig.pos = 'H')
```


```{r, echo = FALSE, message = FALSE}
library(rmarkdown)
library(knitr)
library(kableExtra)
library(dplyr)
```

# How many individuals did we consider and what percentage had missing data?
```{r, echo = FALSE, message = FALSE}
use_this_outcome <- "outcome1"
source("month-six-00.R")
source("month-six-01.R")

missdf %>%
  select(tot_rows, percent_day1, percent_day4, percent_day7, miss_analysis) %>%
  round(., digits = 3) %>%
  kable(booktabs = TRUE, align = rep('c',8),
        col.names = c("Total No. Individuals","Day 1","Day 4","Day 7","Day 1, 4, or 7"),
        row.names = FALSE,
        escape = FALSE,
        caption = "First Column: Total number of individuals in APP ONLY arm (excluding one individual with data issue); Remaining Columns: Percent with no weights") %>%
  kable_styling(full_width = FALSE, latex_options = c("HOLD_position"))
```

# Can we identify APP ONLY arm non-responders during the first week of treatment? (`non-response' as defined in previous SMART study at weeks 2, 4, 8)

```{r, echo = FALSE, message = FALSE}
use_this_outcome <- "outcome1"
source("month-six-00.R")
source("month-six-01.R")
source("month-six-02.R")

tbl_cart_only %>%
  select(sensitivity,specificity) %>%
  round(., digits = 3) %>%
  kable(booktabs = TRUE, align = rep('c',2),
        col.names = c("Sensitivity","Specificity"),
        row.names = TRUE,
        escape = FALSE,
        caption = "CART Only") %>%
  kable_styling(full_width = FALSE, latex_options = c("HOLD_position"))
```


```{r, echo = FALSE, message = FALSE}
use_this_outcome <- "outcome1"
use_miss_rule <- "miss_rule1"
source("month-six-00.R")
source("month-six-01.R")
source("month-six-02.R")
source("month-six-03.R")

tbl_overall %>%
  select(sensitivity,specificity) %>%
  round(., digits = 3) %>%
  kable(booktabs = TRUE, align = rep('c',2),
        col.names = c("Sensitivity","Specificity"),
        row.names = TRUE,
        escape = FALSE,
        caption = "Overall Decision Rule, Option 1: Non-responder if `day 1, 4, or 7' is missing") %>%
  kable_styling(full_width = FALSE, latex_options = c("HOLD_position"))
```


```{r, echo = FALSE, message = FALSE}
use_this_outcome <- "outcome1"
use_miss_rule <- "miss_rule2"
source("month-six-00.R")
source("month-six-01.R")
source("month-six-02.R")
source("month-six-03.R")

tbl_overall %>%
  select(sensitivity,specificity) %>%
  round(., digits = 3) %>%
  kable(booktabs = TRUE, align = rep('c',2),
        col.names = c("Sensitivity","Specificity"),
        row.names = TRUE,
        escape = FALSE,
        caption = "Overall Decision Rule, Option 2: Non-responder if `day 1' is missing") %>%
  kable_styling(full_width = FALSE, latex_options = c("HOLD_position"))
```



```{r, echo = FALSE, message = FALSE}
use_this_outcome <- "outcome1"
use_miss_rule <- "miss_rule3"
source("month-six-00.R")
source("month-six-01.R")
source("month-six-02.R")
source("month-six-03.R")

tbl_overall %>%
  select(sensitivity,specificity) %>%
  round(., digits = 3) %>%
  kable(booktabs = TRUE, align = rep('c',2),
        col.names = c("Sensitivity","Specificity"),
        row.names = TRUE,
        escape = FALSE,
        caption = "Overall Decision Rule, Option 3: Non-responder if `day 4 or 7' is missing") %>%
  kable_styling(full_width = FALSE, latex_options = c("HOLD_position"))
```


```{r, echo = FALSE, message = FALSE}
use_this_outcome <- "outcome1"
use_miss_rule <- "miss_rule4"
source("month-six-00.R")
source("month-six-01.R")
source("month-six-02.R")
source("month-six-03.R")

tbl_overall %>%
  select(sensitivity,specificity) %>%
  round(., digits = 3) %>%
  kable(booktabs = TRUE, align = rep('c',2),
        col.names = c("Sensitivity","Specificity"),
        row.names = TRUE,
        escape = FALSE,
        caption = "Overall Decision Rule, Option 4: Non-responder if either `day 1 and day 4' or `day 7' is missing") %>%
  kable_styling(full_width = FALSE, latex_options = c("HOLD_position"))
```


# Among individuals in the APP ONLY arm, does non-response status based on overall decision rule (Option 4) predict weight loss success at Month X?


```{r, echo = FALSE, message = FALSE}
use_this_outcome <- "outcome1"
use_miss_rule <- "miss_rule4"
source("month-six-00.R")
source("month-six-01.R")
source("month-six-02.R")
source("month-six-03.R")

n_tot <- nrow(dat_reg)
n_participants2 <- nrow(na.omit(dat_reg2))
n_participants3 <- nrow(na.omit(dat_reg3))

tbl_mod_outcome2 %>%
  round(., digits = 3) %>%
  kable(booktabs = TRUE, align = rep('c',4),
        col.names = c("Estimate", "Std. Error", "z value", "Pr(>|z|)"),
        row.names = TRUE,
        escape = FALSE,
        caption = paste("Weight loss success at Month 3: Estimates of Parameters in a Logistic Regression Model"," (N=",n_participants2," participants were used to estimate logistic regression model; ", n_tot-n_participants2," participants had missing weight at 3-mo)", sep="")) %>%
  kable_styling(full_width = FALSE, latex_options = c("HOLD_position"))

tbl_mod_outcome3 %>%
  round(., digits = 3) %>%
  kable(booktabs = TRUE, align = rep('c',4),
        col.names = c("Estimate", "Std. Error", "z value", "Pr(>|z|)"),
        row.names = TRUE,
        escape = FALSE,
        caption = paste("Weight loss success at Month 6: Estimates of Parameters in a Logistic Regression Model"," (N=",n_participants3," participants were used to estimate logistic regression model; ", n_tot-n_participants3," participants had missing weight at 6-mo)", sep="")) %>%
  kable_styling(full_width = FALSE, latex_options = c("HOLD_position"))
```

